# Generated by Django 3.2.23 on 2024-01-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240110_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='decreiption',
            new_name='description',
        ),
    ]
